### ISSUE TITLE
Spaces in compound types are recognized as `@param` field separators

### ISSUE THREAD

**Issue by przepompownia** [claytonrcarter/tree-sitter-phpdoc#35] opened 2024-07-09 13:00 UTC
Let's look at the example below (in Neovim):
```php
/**
 * @param array<array{string, string, bool}> $example
 */
```
![image](https://github.com/claytonrcarter/tree-sitter-phpdoc/assets/11404453/c0391400-a92c-4727-a0e6-952e945474c6)

Maybe it's similar to #26.

**Comment by claytonrcarter** [comment] 2024-09-05 01:31
Thanks for the report! I think that this is more closely related to #27, though, and our lack of support for array shapes. (ie the `{..., ..., ...}` part)

Closing as a duplicate of #27, but please feel free to reopen if you disagree with my conclusion.

**Closed as not planned by claytonrcarter** 2024-09-05 01:31 UTC

**Comment by claytonrcarter** [comment] 2024-09-05 02:47
FYI see #39, which may address this

**Comment by przepompownia** [comment] 2024-09-05 13:37
No problem especially that #27 is still open. Thanks for your attention anyway.
